name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry==2.1.3
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}